server:
  port: 7001
  ​
eureka:
  instance:
    #eureka服务端实例名称
    hostname: localhost
  client:
    #表示不向注册中心注册自己,注册中心不需要将自己注册进注册中心
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责就是维护服务实例,并不去检索服务
    fetch-registry: false
    service-url:
      #设置以eureka server交互的地址,查询服务和注册服务都需要遵循该地址.  此处的${eureka.instance.hostname}就是注入上面的localhost
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/