server:
  #每个微服务都有自己的端口
  port: 80

logging:
  level:
    root: info

#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      #注册地址
      defaultZone: http://root:root@127.0.0.1:7001/eureka
    #因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    #是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    #eureka管理页面配置的微服务名称
    instance-id: oreder80
    #eureka管理页面可以看到微服务的IP地址,鼠标放到微服务名称上,页面左下角显示IP
    prefer-ip-address: true

#开启容错机制
feign:
  hystrix:
    enabled: true

spring:
  application:
    #注册到eureka中的名称
    name: cloud-eureka-order