server:
  #每个微服务都有自己的端口
  port: 8001

spring:
  application:
    #每一个微服务都有自己的名称
    name: cloud-provider-service
  datasource:
    type: ${mysql.type}
    driver-class-name: ${mysql.driver-class-name}
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

mybatis-plus:
  mapper-locations: classpath:com/cc/**/mapper/*.xml

logging:
  level:
    root: debug