server:
  port: 7002

eureka:
  server:
    #开发环境下禁用自我保护模式
    enable-self-preservation: false
  client:
    #表示不向注册中心注册自己,注册中心不需要将自己注册进注册中心
    register-with-eureka: true
    #false表示自己就是注册中心，我的职责就是维护服务实例,并不去检索服务
    fetch-registry: true
    service-url:
      #设置以eureka server交互的地址,查询服务和注册服务都需要遵循该地址.  此处的${eureka.instance.hostname}就是注入上面的localhost
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:7001/eureka/
  instance:
    hostname: localhost

spring:
  application:
    #注册到eureka中的名称
    name: cloud-eureka-server
  security:
    user: #配置用户的账号信息
      name: root
      password: root