spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://node01:3306/spirngcloud?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: root